version: "3.8"

services:
  app:
    image: python:3.11
    container_name: python_app
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      bash || tail -f /dev/null
      "
